# Generated by Django 4.2.20 on 2025-04-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0018_task_success_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='intended_date_kwarg',
        ),
        migrations.AddField(
            model_name='schedule',
            name='country',
            field=models.CharField(choices=[('COL', 'COLOMBIA'), ('CHL', 'CHILE'), ('CRI', 'COSTA RICA'), ('ECU', 'ECUADOR'), ('PAN', 'PANAMA'), ('PER', 'PERU')], default='COL', max_length=50, verbose_name='country'),
        ),
    ]
